install.packages("readxl")
library(tidyverse)
library(readxl)
dataset1 <- read_excel("dataset1.xls")
View(dataset1)

df <- read_excel("dataset1.xls")
results <- count(df, df$Title)
View(results)

dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Aldermen", "Alderman")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Clerk", "Clerk of Court")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Constable(s)", "Constable")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Council Member at Large", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Council Member I", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Council Member II", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Council Member III", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Council Member(s)", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Councilman", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Councilman at Large", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Councilmember", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Councilmember at Large", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Council Member at Large", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Councilmen", "Council Member")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Judge, Court of Appeal", "Judge")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "District Judge", "Judge")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "City Judge", "Judge")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "City Judge, City Court", "Judge")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Judge, Family Court", "Judge")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Justice of the Peace(s)", "Justice of the Peace")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Justice of the Peace, Parishwide", "Justice of the Peace")
dataset1$Title <-- replace (dataset1$Title, dataset1$Title == "Mayor-President", "Mayor")

count(df, df$Title)

results <- count(df, df$Title)
View(results)
View(dataset1_1_)
#95/100 -5 did not push data
